### PR TITLE
Parallax capabilities

### PR DESCRIPTION
**Pull request by razekteixeira**
- sets opactity to 0 if not title is provided per slide
- added parallax features
- possibility to enable/disable parallax
- posisbiliby to set parallax background image
- possibility to set parallax speed
- possibility to set parallax speed of elements
	- title
	- image
	- text

### CODE REVIEW

**Comment by razekteixeira** [comment]
*** The documentation on README is missing, if @valnub and @nolimits4web confirms the pull request I'll to the documentation to integrate.


Best Regards,
César Teixeira

**Comment by valnub** [comment]
Can you post a demo?

**Comment by razekteixeira** [comment]
Please take a look:
http://razekcloudserver.no-ip.org/Framework7WelcomeScreen/example/

Options passed in example: 
`var options = {
		'bgcolor': '#0da6ec',
		'fontcolor': '#fff',
		'parallax': true,
		'parallaxBackgroundImage': 'http://lorempixel.com/900/600/nightlife/2/', // parallax default background image
		'parallaxBackground': '-23%', // parallax default background effect
		'parallaxSlideElements': {
			title: -100,
			subtitle: -200,
			text: -300
		},
		'onOpened': function() {
			console.log("welcome screen opened");
		},
		'onClosed': function() {
			console.log("welcome screen closed");
		}`

**Comment by razekteixeira** [comment]
@valnub README has been updated ;)

As soon as you can, please accept the PR ;)

Best Regards,
César Teixeira

**Comment by valnub** [comment]
Thanks, can you explain a bit more in detail what the values -100, -200, -300 are for and why they are negative?
Everything else is fine! 👍 
Thanks :-)

**Comment by razekteixeira** [comment]
@valnub I just added a note explaining what and why the number and percentage values are passed to the swiper. I hope everything is fine ;)

**Pull request merged**
